title: 'CIS Summer School Hyderabad'
default_lang: en
author:
  name: 'CIS Hyderabad'
  email: webmaster@ieeehyd.org
taxonomies:
  - category
  - tag
metadata:
  description: 'CIS Summer School IEEE Hyderabad Section'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
